Agrobanco.SCC/Agrobanco.SCC.Web/Controllers/ConfiguracionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Agrobanco.SCC.BLL;
using Agrobanco.SCC.DAL.Entidades;
using Agrobanco.SCC.Web.Helpers;
using Agrobanco.SCC.Web.Models;
using PagedList;

namespace Agrobanco.SCC.Web.Controllers
{
    public class ConfiguracionController : BaseController
    {
        // GET: Configuracion
        public ActionResult Index()
        {                       
            ViewBag.VencimientoDesde = string.Empty;
            ViewBag.VencimientoHasta = string.Empty;

            CargarDatosIniciales();
            var onePageListaReporte = ObtenerListaReporteBusqueda(1, 10, "0", string.Empty, string.Empty);

            return View(onePageListaReporte);
        }

        [HttpPost]
        public ActionResult Buscar(int? page, string hdListaArea, string fecVencimientoDesde, string fecVencimientoHasta)
        {
            ViewBag.hdListaArea = hdListaArea;
            ViewBag.fecVencimientoDesde = fecVencimientoDesde;
            ViewBag.fecVencimientoHasta = fecVencimientoHasta;
            try
            {
                var onePageListaReporte = ObtenerListaReporteBusqueda(page, 10, hdListaArea, fecVencimientoDesde, fecVencimientoHasta);

                return PartialView("_Lista", onePageListaReporte);
            }
            catch (Exception ex)
            {
                GenerarLog(ex.Message);
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, ex.Message);
            }            
        }

        [HttpPost]
        public JsonResult RegistrarReporte(Reporte reporte)
        {
            ConfiguracionBLL configuracion = new ConfiguracionBLL();
            RespuestaOperacion response = new RespuestaOperacion();

            try
            {
                 var usuarioSesion = (ResultadoObtenerModel<Helpers.Usuario>)Session["UsuarioSCC"];

                reporte.UsuCreacion = usuarioSesion.Model.UsuarioWeb;
                reporte.UsuActualizacion = usuarioSesion.Model.UsuarioWeb;

                bool validacionExitosa = true;

                if (!string.IsNullOrEmpty(reporte.NombreReporte))
                {
                    validacionExitosa = configuracion.ValidarNombreReporte(reporte.CodigoReporte, reporte.NombreReporte);
                }                

                if (!validacionExitosa)
                {
                    response = new RespuestaOperacion { Resultado = 0, Mensaje = "El nombre del reporte ingresado, ya se encuentra registrado" };

                    return Json(response);
                }

                int resultadoRegistro = configuracion.RegistrarReporte(reporte);

                response = new RespuestaOperacion { Resultado = 1, Mensaje = "OK" };
            }
            catch (Exception ex)
            {
                GenerarLog(ex.Message);
                response = new RespuestaOperacion { Resultado = 0, Mensaje = "Ha ocurrido un error en la aplicación" };
            }

            return Json(response);
        }

        [HttpGet]
        public JsonResult ObtenerReporte(int codigoReporte)
        {
            ConfiguracionBLL configuracion = new ConfiguracionBLL();
            RespuestaOperacion response = new RespuestaOperacion();

            try
            {                
                List<Reporte> listaReporte = configuracion.ObtenerListaReporte(codigoReporte);

                var reporte = listaReporte.FirstOrDefault();

                response = new RespuestaOperacion { Resultado = 1, Mensaje = "OK", Data = reporte};
            }
            catch (Exception ex)
            {
                GenerarLog(ex.Message);
                response = new RespuestaOperacion { Resultado = 0, Mensaje = "Ha ocurrido un error en la aplicación" };
            }

            return Json(response, JsonRequestBehavior.AllowGet);
        }

        //private IPagedList<ReporteModel> ObtenerListaReporte(int? page, int pageSize, List<int> listaArea, string vencimientoDesde, string vencimientoHasta)
        //{
        //    List<ReporteModel> listaReporte = new List<ReporteModel>();
        //    int pageNumber = page ?? 1;
            
        //    ConfiguracionBLL configuracion = new ConfiguracionBLL();

        //    DateTime? dtVencimientoDesde = string.IsNullOrEmpty(vencimientoDesde) ? (DateTime?)null : Convert.ToDateTime(vencimientoDesde);
        //    DateTime? dtVencimientoHasta = string.IsNullOrEmpty(vencimientoHasta) ? (DateTime?)null : Convert.ToDateTime(vencimientoHasta);

        //    var reportes = configuracion.ObtenerListaReporte(listaArea, dtVencimientoDesde, dtVencimientoHasta);
        //    //var reportes = configuracion.ObtenerListaReporteBusqueda(listaArea, dtVencimientoDesde, dtVencimientoHasta);

        //    foreach (var item in reportes)
        //    {
        //        ReporteModel reporteModel = new ReporteModel();

        //        reporteModel.CodReporte = item.CodigoReporte;
        //        reporteModel.Nombre = item.NombreReporte;
        //        reporteModel.Descripcion = item.Descripcion;
        //        reporteModel.Entidad = item.Empresa;
        //        reporteModel.AreaResponsable = item.AreaResponsable;
        //        reporteModel.Frecuencia = item.Frecuencia;
        //        reporteModel.Plazo = string.Concat(item.Plazo, " días");
        //        reporteModel.ProximoVencimiento = string.Concat(item.ProximoVencimiento.Day.ToString().PadLeft(2, '0'), "/", item.ProximoVencimiento.Month.ToString().PadLeft(2, '0'), "/", item.ProximoVencimiento.Year.ToString());
        //        reporteModel.ResponsablePrincipal = item.ResponsablePrincipal;

        //        listaReporte.Add(reporteModel);
        //    }


        //    var listaResultado = listaReporte.ToPagedList(pageNumber, pageSize);

        //    return listaResultado;
        //}

        private IPagedList<ReporteModel> ObtenerListaReporteBusqueda(int? page, int pageSize, string listaArea, string vencimientoDesde, string vencimientoHasta)
        {
            List<ReporteModel> listaReporte = new List<ReporteModel>();
            int pageNumber = page ?? 1;

            ConfiguracionBLL configuracion = new ConfiguracionBLL();

            DateTime? dtVencimientoDesde = null;
            DateTime? dtVencimientoHasta = null;

            if (!string.IsNullOrEmpty(vencimientoDesde))
            {

                string[] arrFecha = vencimientoDesde.Split('/');
                string dia = arrFecha[0];
                string mes = arrFecha[1];
                string anio = arrFecha[2];

                dtVencimientoDesde = new DateTime(Convert.ToInt32(anio), Convert.ToInt32(mes), Convert.ToInt32(dia));
            }

            if (!string.IsNullOrEmpty(vencimientoHasta))
            {
                string[] arrFecha = vencimientoHasta.Split('/');
                string dia = arrFecha[0];
                string mes = arrFecha[1];
                string anio = arrFecha[2];

                dtVencimientoHasta = new DateTime(Convert.ToInt32(anio), Convert.ToInt32(mes), Convert.ToInt32(dia));
            }

            if (string.IsNullOrEmpty(listaArea))
            {
                listaArea = "0";
            }           

            //var reportes = configuracion.ObtenerListaReporte(listaArea, dtVencimientoDesde, dtVencimientoHasta);
            var reportes = configuracion.ObtenerListaReporteBusqueda(listaArea, dtVencimientoDesde, dtVencimientoHasta);

            foreach (var item in reportes)
            {
                ReporteModel reporteModel = new ReporteModel();

                reporteModel.CodReporte = item.CodigoReporte;
                reporteModel.Nombre = item.NombreReporte;
                reporteModel.Descripcion = item.Descripcion;
                reporteModel.Entidad = item.Empresa;
                reporteModel.AreaResponsable = item.AreaResponsable;
                reporteModel.Frecuencia = item.Frecuencia;
                reporteModel.Plazo = string.Concat(item.Plazo, " días");
                reporteModel.ProximoVencimiento = string.Concat(item.ProximoVencimiento.Day.ToString().PadLeft(2, '0'), "/", item.ProximoVencimiento.Month.ToString().PadLeft(2, '0'), "/", item.ProximoVencimiento.Year.ToString());
                reporteModel.ResponsablePrincipal = item.ResponsablePrincipal;

                listaReporte.Add(reporteModel);
            }

            var listaResultado = listaReporte.ToPagedList(pageNumber, pageSize);

            return listaResultado;
        }

        

        private void CargarDatosIniciales()
        {
            ParametriaBLL parametria = new ParametriaBLL();
            List<ElementoBasico> areasFiltro = new List<ElementoBasico>();
            var areas = parametria.ObtenerListaArea();
            //areasFiltro.Add(new ElementoBasico { Codigo = string.Empty, Descripcion = "Todos", Selected = true, Disabled = true });

            foreach (var item in areas)
            {
                ElementoBasico elemento = new ElementoBasico();
                elemento.Codigo = item.CodigoElemento.ToString();
                elemento.Descripcion = item.Descripcion;
                
                areasFiltro.Add(elemento);
            }

            ViewBag.ListaAreaResponsable = areasFiltro;
            ViewBag.ListaArea = parametria.ObtenerListaArea();
            ViewBag.ListaEmpresa = parametria.ObtenerListaEmpresa();
            ViewBag.ListaFrecuencia = parametria.ObtenerListaFrecuencia();
            ViewBag.ListaMedioEnvio = parametria.ObtenerListaMedioEnvio();
            ViewBag.ListaUsuario = parametria.ObtenerListaUsuario();
        }
    }
}

Agrobanco.SCC/Agrobanco.SCC.Web/Views/Configuracion/Index.cshtml
@using PagedList;
@using Agrobanco.SCC.Web.Models;
@model IPagedList<ReporteModel>
@{
    /**/

    ViewBag.Title = "Index";
    List<ElementoBasico> areasResponsables = ViewBag.ListaAreaResponsable;

}

<div class="section no-padding">
    <div class="row col s12 no-mar-bot">
        <div class="section no-mar-bot">
            <div class="col s12 m12 l12">
                <h1 class="title">Configuración</h1>
            </div>
        </div>
    </div>
</div>

<div class="card-panel row layout-card-gray-2">
    <div class="row">
        <div class="col s12 m12 l12">
            <span class="card-panel-title">Buscar por:</span>
        </div>
    </div>

    <div class="row no-mar-bot">
        @using (Ajax.BeginForm("Buscar", "Configuracion",
               new AjaxOptions
               {
                   HttpMethod = "POST",
                   InsertionMode = InsertionMode.Replace,
                   UpdateTargetId = "configuracion-grid",
                   LoadingElementId = "modal_loading_agro",
                   OnFailure = "errorAjax"
               }))
        {
            <input type="hidden" id="hdListaArea" name="hdListaArea" value="0" />

            <div class="col s12 m6 l4">
                <div class="input-field input-field-common col s12">
                    <label class="label active" for="cbo-area-responsable">Área Responsable</label>
                    <select name="cbo-area-responsable" id="cbo-area-responsable" multiple>
                        <option value="" disabled selected>Seleccione</option>
                        @foreach (var item in areasResponsables)
                        {
                            @*if (item.Selected)
                                {
                                    string strDisabled = (item.Disabled) ? "disabled" : string.Empty;
                                    <option value="@item.Codigo" @strDisabled selected>@item.Descripcion</option>
                                }
                                else*@
                            {
                                <option value="@item.Codigo">@item.Descripcion</option>
                            }

                        }
                    </select>
                </div>
            </div>
            <div class="col s12 m6 l2">
                <div class="input-field input-field-common col s12">
                    <i class="material-icons icon-suffix">date_range</i>
                    <input name="fecVencimientoDesde" id="fecVencimientoDesde" type="text" autocomplete="off" class="datepicker">
                    <label for="fecVencimientoDesde" class="label active">Vencimiento (Desde)</label>
                </div>
            </div>
            <div class="col s12 m6 l2">
                <div class="input-field input-field-common col s12">
                    <i class="material-icons icon-suffix">date_range</i>
                    <input name="fecVencimientoHasta" id="fecVencimientoHasta" type="text" autocomplete="off" class="datepicker">
                    <label for="fecVencimientoHasta" class="label active">Vencimiento (Hasta)</label>
                </div>
            </div>
            <div class="col s2 m6 l2 offset-s7">
                <button id="btnBuscar" class="btn waves-effect waves-light btn-default-resize " style="margin-top:23px;">
                    <span>Buscar</span>
                    <i class="material-icons">search</i>
                </button>
            </div>
        }

        <div class="col s2 m6 l2 offset-s1">
            <button class="btn btn-default-resize" style="margin-top:23px;" id="btn-nuevo">
                <span>Nuevo</span>
                <i class="material-icons">add</i>
            </button>
        </div>

    </div>

</div>


<div class="row" id="configuracion-grid">
    @{
        Html.RenderPartial("_Lista", Model);
    }
</div>

<div>
    @Html.Partial("~/Views/Configuracion/_ReporteModal.cshtml")
    @*@Html.Partial("~/Views/Usuario/_ModalConfirmarRegistro.cshtml")*@
</div>

@section scripts{
    @Scripts.Render("~/Scripts/app/Configuracion.js")
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    
    <script>
        function errorAjax() {
            app.Funciones.msgError("Ha ocurrido un error en la aplicación");
        }
    </script>
}

Agrobanco.SCC/Agrobanco.SCC.Web/Views/Configuracion/_Lista.cshtml
@using PagedList;
@using PagedList.Mvc;
@using Agrobanco.SCC.Web.Models;
@model IPagedList<ReporteModel>

<div class="col s6 m6 l12 right-align text-right">
    <ul class="pagination no-margin">

        @Html.PagedListPager(Model,
                                page => Url.Action("Buscar",
                                                    new { page = page, hdListaArea = ViewBag.hdListaArea, fecVencimientoDesde = ViewBag.fecVencimientoDesde, fecVencimientoHasta = ViewBag.fecVencimientoHasta }
                                        ),
                                PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "POST", UpdateTargetId = "configuracion-grid", LoadingElementId = "modal_loading_agro" }))
    </ul>
</div>

<div class="col s12 table-listas">
    <div class="table-common table-common-mediano">
        <div class="row row-title hide-on-small-only no-pad-bot">

            <div class="col s12 m2">Reporte</div>
            <div class="col s12 m2">Entidad</div>
            <div class="col s12 m2">Área Responsable</div>
            <div class="col s12 m1">Responsable Principal</div>
            <div class="col s12 m2">Frecuencia</div>
            <div class="col s12 m1">Plazo</div>
            <div class="col s12 m1">Próximo Vencimiento</div>
            <div class="col s12 m1">Editar</div>
        </div>

        @foreach (var item in Model)
        {
        <div class="row">
            <div class="col s12 m2">
                <p>@Html.DisplayFor(modelItem => item.Nombre)</p>
                <p>@Html.DisplayFor(modelItem => item.Descripcion)</p>
            </div>
            <div class="col s12 m2">
                @Html.DisplayFor(modelItem => item.Entidad)
            </div>
            <div class="col s12 m2">
                @Html.DisplayFor(modelItem => item.AreaResponsable)
            </div>
            <div class="col s12 m1">
                @Html.DisplayFor(modelItem => item.ResponsablePrincipal)
            </div>
            <div class="col s12 m2">
                @Html.DisplayFor(modelItem => item.Frecuencia)
            </div>
            <div class="col s12 m1">
                @Html.DisplayFor(modelItem => item.Plazo)
            </div>
            <div class="col s12 m1">
                @Html.DisplayFor(modelItem => item.ProximoVencimiento)
            </div>
            <div class="col s12 m1">
                <i onclick="configuracion.Funciones.OpenReporteModal(2,'@item.CodReporte')" class="material-icons" style="cursor: pointer;" name="action">create</i>
            </div>
        </div>
        }
    </div>
</div>