Agrobanco.SCC/Agrobanco.SCC.Web/Controllers/CumplimientoController.cs
using Agrobanco.SCC.BLL;
using Agrobanco.SCC.DAL;
using Agrobanco.SCC.DAL.Entidades;
using Agrobanco.SCC.Web.Helpers;
using Agrobanco.SCC.Web.Models;
using ClosedXML.Excel;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Agrobanco.SCC.Web.Controllers
{
    public class CumplimientoController : BaseController
    {
        // GET: Cumplimiento
        public ActionResult Index()
        {
            ViewBag.VencimientoDesde = string.Empty;
            ViewBag.VencimientoHasta = string.Empty;

            CargarDatosIniciales();

            var model = ObtenerListaEnvioBusquedaModel(1, 10, null, null, null, null);

            return View(model);
        }


        private void CargarDatosIniciales()
        {
            ParametriaBLL parametria = new ParametriaBLL();
            ConfiguracionBLL configuracion = new ConfiguracionBLL();
            List<ElementoBasico> areasFiltro = new List<ElementoBasico>();
            var areas = parametria.ObtenerListaArea();
            var usuarios = parametria.ObtenerListaUsuario();
            List<Reporte> reportesFiltrados = new List<Reporte>();
            foreach (var item in areas)
            {
                ElementoBasico elemento = new ElementoBasico();
                elemento.Codigo = item.CodigoElemento.ToString();
                elemento.Descripcion = item.Descripcion;

                areasFiltro.Add(elemento);
            }

            reportesFiltrados = configuracion.ObtenerListaReporte();
            var usuarioSesion = (ResultadoObtenerModel<Helpers.Usuario>)Session["UsuarioSCC"];
            var usuario = usuarios.Where(u => u.WebUser == usuarioSesion.Model.UsuarioWeb).FirstOrDefault();

            var usersCumplimiento = parametria.ObtenerListaCorreosCumplimiento();

            if (usuario == null)
            {
                return;
            }

            if (!usersCumplimiento.Where(uc => uc.Valor == usuario.WebUser).Any())
            {
                reportesFiltrados = reportesFiltrados.Where(r => r.CodResponsablePrincipal == usuario.CodUsuario ||
                                                                r.CodResponsableAlterno == usuario.CodUsuario ||
                                                                r.CodGerenteResponsable == usuario.CodUsuario ||
                                                                r.CodCoordinador == usuario.CodUsuario).ToList();
            }

            ViewBag.ListaReportes = reportesFiltrados;
            ViewBag.ListaAreaResponsable = areasFiltro;
            ViewBag.ListaEntidad = parametria.ObtenerListaEmpresa();
            ViewBag.ListaFrecuencia = parametria.ObtenerListaFrecuencia();
            ViewBag.ListaUsuario = usuarios;
            ViewBag.ListaMotivo = parametria.ObtenerListaMotivo();
        }

        private IPagedList<EnvioModel> ObtenerListaEnvioBusquedaModel(int? page, int pageSize, string listaEntidad, string listaFrecuencia, string vencimientoDesde, string vencimientoHasta)
        {
            List<EnvioModel> envioModel = new List<EnvioModel>();
            int pageNumber = page ?? 1;
            
            var listaEnvio = ObtenerListaEnvioBusqueda(listaEntidad, listaFrecuencia, vencimientoDesde, vencimientoHasta);

            foreach (var item in listaEnvio)
            {
                EnvioModel envioM = new EnvioModel();

                envioM.CodEnvio = item.CodEnvio;
                envioM.CodReporte = item.CodReporte;
                envioM.NombreReporte = item.NombreReporte;
                envioM.Entidad = item.Entidad;
                envioM.AreaResponsable = item.AreaResponsable;
                envioM.ResponsablePrincipal = item.ResponsablePrincipal;
                envioM.Frecuencia = item.Frecuencia;
                envioM.FechaVencimiento = item.FechaVencimiento.ToString();
                envioM.FechaEnvio = item.FechaEnvio.ToString();

                envioModel.Add(envioM);
            }

            var listaResultado = envioModel.ToPagedList(pageNumber, pageSize);

            return listaResultado;
        }

        private List<Envio> ObtenerListaEnvioBusqueda(string listaEntidad, string listaFrecuencia, string vencimientoDesde, string vencimientoHasta)
        {
            CumplimientoBLL cumplimiento = new CumplimientoBLL();
            ParametriaBLL parametria = new ParametriaBLL();

            DateTime? dtVencimientoDesde = null;
            DateTime? dtVencimientoHasta = null;

            if (!string.IsNullOrEmpty(vencimientoDesde))
            {

                string[] arrFecha = vencimientoDesde.Split('/');
                string dia = arrFecha[0];
                string mes = arrFecha[1];
                string anio = arrFecha[2];

                dtVencimientoDesde = new DateTime(Convert.ToInt32(anio), Convert.ToInt32(mes), Convert.ToInt32(dia));
            }

            if (!string.IsNullOrEmpty(vencimientoHasta))
            {
                string[] arrFecha = vencimientoHasta.Split('/');
                string dia = arrFecha[0];
                string mes = arrFecha[1];
                string anio = arrFecha[2];

                dtVencimientoHasta = new DateTime(Convert.ToInt32(anio), Convert.ToInt32(mes), Convert.ToInt32(dia));
            }

            if (string.IsNullOrEmpty(listaEntidad))
            {
                listaEntidad = "0";
            }

            if (string.IsNullOrEmpty(listaFrecuencia))
            {
                listaFrecuencia = "0";
            }

            var listaEnvio = cumplimiento.ObtenerListaEnvioBusqueda(listaEntidad, listaFrecuencia, dtVencimientoDesde, dtVencimientoHasta);
            var usuarios = parametria.ObtenerListaUsuario();
            var usuarioSesion = (ResultadoObtenerModel<Helpers.Usuario>)Session["UsuarioSCC"];
            var usuario = usuarios.Where(u => u.WebUser == usuarioSesion.Model.UsuarioWeb).FirstOrDefault();

            var usersCumplimiento = parametria.ObtenerListaCorreosCumplimiento();

            if (usuario == null)
            {
                return new List<Envio>();
            }

            if (!usersCumplimiento.Where(uc => uc.Valor == usuario.WebUser).Any())
            {
                listaEnvio = listaEnvio.Where(e => e.CodResponsablePrincipal == usuario.CodUsuario ||
                                                                e.CodResponsableAlterno == usuario.CodUsuario ||
                                                                e.CodGerenteResponsable == usuario.CodUsuario ||
                                                                e.CodCoordinador == usuario.CodUsuario).ToList();
            }

            return listaEnvio;
        }

        [HttpPost]
        public ActionResult Buscar(int? page, string hdListaEntidad, string hdListaFrecuencia, string fecVencimientoDesde, string fecVencimientoHasta)
        {
            ViewBag.hdListaEntidad = hdListaEntidad;
            ViewBag.hdListaFrecuencia = hdListaFrecuencia;
            ViewBag.fecVencimientoDesde = fecVencimientoDesde;
            ViewBag.fecVencimientoHasta = fecVencimientoHasta;
            try
            {
                var onePageListaEnvio = ObtenerListaEnvioBusquedaModel(page, 10, hdListaEntidad, hdListaFrecuencia, fecVencimientoDesde, fecVencimientoHasta);

                return PartialView("_ListaCumplimiento", onePageListaEnvio);
            }
            catch (Exception ex)
            {
                GenerarLog(ex.Message);
                throw new HttpException(500, ex.Message);
            }            
        }

        [HttpPost]
        public ActionResult RegistrarEnvio(Envio envio)
        {
            CumplimientoBLL cumplimiento = new CumplimientoBLL();
            RespuestaOperacion response = new RespuestaOperacion();

            try
            {
                System.IO.Stream fileContent = null;

                if (Request.Files.Count > 0)
                {
                    HttpPostedFileBase file = Request.Files[0];
                    int fileSize = file.ContentLength;
                    string fileName = file.FileName;
                    string mimeType = file.ContentType;
                    fileContent = file.InputStream;                    
                }

                var usuarioSesion = (ResultadoObtenerModel<Helpers.Usuario>)Session["UsuarioSCC"];
                envio.UsuarioCreacion = usuarioSesion.Model.UsuarioWeb;

                DateTime nuevaFechaVencimiento = cumplimiento.RegistrarEnvio(envio, fileContent);
                string strFechaVencimiento = string.Concat(nuevaFechaVencimiento.Day.ToString().PadLeft(2, '0'), "/", nuevaFechaVencimiento.Month.ToString().PadLeft(2, '0'), "/", nuevaFechaVencimiento.Year.ToString());

                response = new RespuestaOperacion { Resultado = 1, Mensaje = "OK", Data = new { nuevaFechaVencimiento, strFechaVencimiento } };
            }
            catch (Exception ex)
            {
                GenerarLog(ex.Message);
                response = new RespuestaOperacion { Resultado = 0, Mensaje = "Ha ocurrido un error en la aplicación" };
            }

            return Json(response);
        }

        [HttpGet]
        public JsonResult ObtenerEnvio(int codEnvio)
        {
            CumplimientoBLL cumplimiento = new CumplimientoBLL();
            RespuestaOperacion response = new RespuestaOperacion();

            try
            {
                List<Envio> listaEnvio = cumplimiento.ObtenerListaEnvio(codEnvio);

                var envio = listaEnvio.FirstOrDefault();
                bool dentroDelPlazo = false;

                if (envio.CodEstadoEnvio == (int)Enums.EstadoEnvio.Enviado)
                {
                    dentroDelPlazo = (envio.FechaEnvio > envio.FechaVencimiento) ? false : true;
                }

Agrobanco.SCC/Agrobanco.SCC.Web/Views/Cumplimiento/Index.cshtml
@using PagedList;
@using Agrobanco.SCC.Web.Models;
@using Agrobanco.SCC.DAL.Entidades;
@model IPagedList<EnvioModel>

@{
    List<Parametro> entidades = ViewBag.ListaEntidad;
    List<Parametro> frecuencias = ViewBag.ListaFrecuencia;
}

<div class="section no-padding">
    <div class="row col s12 no-mar-bot">
        <div class="section no-mar-bot">
            <div class="col s12 m12 l12">
                <h1 class="title">Cumplimiento</h1>
            </div>
        </div>
    </div>
</div>

<div class="card-panel row layout-card-gray-2">
    <div class="row">
        <div class="col s12 m12 l12">
            <span class="card-panel-title">Buscar por:</span>
        </div>
    </div>

    <div class="row no-mar-bot">
        @using (Ajax.BeginForm("Buscar", "Cumplimiento",
               new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "cumplimiento-grid", LoadingElementId = "modal_loading_agro"
               , OnFailure = "app.Funciones.msgError('Ha ocurrido un error en la aplicación')"
               }))
        {
            <input type="hidden" id="hdListaEntidad" name="hdListaEntidad" value="0" />
            <input type="hidden" id="hdListaFrecuencia" name="hdListaFrecuencia" value="0" />

            <div class="col s12 m6 l2">
                <div class="input-field input-field-common col s12">
                    <label class="label active" for="cbo-entidad">Entidad</label>
                    <select name="cbo-entidad" id="cbo-entidad" multiple>
                        <option value="" disabled selected>Seleccione</option>
                        @foreach (var item in entidades)
                        {
                            <option value="@item.CodigoElemento">@item.Descripcion</option>
                        }
                    </select>
                </div>
            </div>

            <div class="col s12 m6 l2">
                <div class="input-field input-field-common col s12">
                    <label class="label active" for="cbo-frecuencia">Frecuencia</label>
                    <select name="cbo-frecuencia" id="cbo-frecuencia" multiple>
                        <option value="" disabled selected>Seleccione</option>
                        @foreach (var item in frecuencias)
                        {
                            <option value="@item.CodigoElemento">@item.Descripcion</option>
                        }
                    </select>
                </div>
            </div>

            <div class="col s12 m6 l2">
                <div class="input-field input-field-common col s12">
                    <i class="material-icons icon-suffix">date_range</i>
                    <input name="fecVencimientoDesde" id="fecVencimientoDesde" type="text" autocomplete="off" class="datepicker">
                    <label for="fecVencimientoDesde" class="label active">Vencimiento (Desde)</label>
                </div>
            </div>
            <div class="col s12 m6 l2">
                <div class="input-field input-field-common col s12">
                    <i class="material-icons icon-suffix">date_range</i>
                    <input name="fecVencimientoHasta" id="fecVencimientoHasta" type="text" autocomplete="off" class="datepicker">
                    <label for="fecVencimientoHasta" class="label active">Vencimiento (Hasta)</label>
                </div>
            </div>
            <div class="col s2 m6 l2 offset-s7">
                <button id="btnBuscar" class="btn waves-effect waves-light btn-default-resize " style="margin-top:23px;">
                    <span>Buscar</span>
                    <i class="material-icons">search</i>
                </button>
            </div>
        }

        <div class="col s2 m6 l2 offset-s1">
            <button class="btn btn-default-resize" style="margin-top:23px;" id="btn-nuevo">
                <span>Nuevo</span>
                <i class="material-icons">add</i>
            </button>
        </div>

    </div>

</div>

<div class="row" id="cumplimiento-grid">
    @{
        Html.RenderPartial("_ListaCumplimiento", Model);
    }
</div>

<div>
    @Html.Partial("~/Views/Cumplimiento/_EnvioModal.cshtml")    
</div>


@section scripts{
    @Scripts.Render("~/Scripts/app/Cumplimiento.js")
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
}

Agrobanco.SCC/Agrobanco.SCC.Web/Views/Cumplimiento/_EnvioModal.cshtml
@using Agrobanco.SCC.Web.Models;
@using Agrobanco.SCC.DAL.Entidades;
@{
    List<ElementoBasico> areasResponsables = ViewBag.ListaAreaResponsable;

}

@using (Html.BeginForm("#", "", FormMethod.Post, new { id = "frmEnvioModal" }))
{
    @Html.AntiForgeryToken()

<div id="modal-envio" class="modal modal-l">
    <div style="display:none">
        <label id="hdTipoOperacion"></label>
        <label id="hdCodigoEnvio"></label>
        <label id="hdCodigoSustento"></label>
    </div>

    <div class="modal-header">
        <h4 class="title"><span id="textModalTitulo"></span></h4>
        <i class="material-icons btn-close modal-action modal-close">close</i>
    </div>

    <div class="modal-content content-input">
        <div class="row">
            <div class="col s12 m6 l12">
                <div class="input-field input-field-common col s12">
                    <label class="label active" for="cboReporte">Reporte *</label>
                    <select name="cboReporte" id="cboReporte" class="select-require" required>
                        <option value="">Seleccione</option>
                        @foreach (Reporte item in ViewBag.ListaReportes)
                        {
                            <option value="@item.CodigoReporte" data-entidad="@item.CodigoEmpresa" data-area-responsable="@item.CodAreaResponsable"
                                    data-gerente-responsable="@item.CodGerenteResponsable" data-responsable-p="@item.CodResponsablePrincipal" data-responsable-a="@item.CodResponsableAlterno"
                                    data-dia-vencimiento="@item.ProximoVencimiento.Day" data-mes-vencimiento="@item.ProximoVencimiento.Month" data-anio-vencimiento="@item.ProximoVencimiento.Year"
                                    data-nombre-reporte="@item.NombreReporte" data-tipo-calculo="@item.TipoCalculo" data-cod-frecuencia="@item.CodFrecuencia">@item.NombreReporte - @item.Descripcion</option>
                        }
                    </select>
                </div>
            </div>
        </div>        
        <div class="row">
            <div class="col s12 m6 l4">
                <div class="input-field input-field-common col s12 disabled">
                    <label class="label active" for="cboEntidadModal">Entidad</label>
                    <select name="cboEntidadModal" id="cboEntidadModal" class="select-require" required>
                        <option value="">Seleccione</option>
                        @foreach (Parametro item in ViewBag.ListaEntidad)
                        {

                            <option value="@item.CodigoElemento">@item.Descripcion</option>

                        }
                    </select>
                </div>
            </div>

            <div class="col s12 m6 l4">
                <div class="input-field input-field-common col s12 disabled">
                    <label class="label active" for="cboAreaResModal">Área Responsable</label>
                    <select name="cboAreaResModal" id="cboAreaResModal" class="select-require" required>
                        <option value="">Seleccione</option>
                        @foreach (ElementoBasico item in areasResponsables)
                        {
                            <option value="@item.Codigo">@item.Descripcion</option>
                        }
                    </select>
                </div>
            </div>

            <div class="col s12 m6 l4">
                <div class="input-field input-field-common col s12 disabled">
                    <label class="label active" for="cboGerenteResponsableModal">Gerente Responsable</label>
                    <select name="cboGerenteResponsableModal" id="cboGerenteResponsableModal" class="select-require" required>
                        <option value="">Seleccione</option>
                        @foreach (Usuario item in ViewBag.ListaUsuario)
                        {
                            <option value="@item.CodUsuario">@item.Nombres</option>
                        }
                    </select>
                </div>
            </div>
        </div>        
        <div class="row">
            <div class="col s12 m6 l4">
                <div class="input-field input-field-common col s12 disabled">
                    <label class="label active" for="cboResPrincipalModal">Responsable Principal</label>
                    <select name="cboResPrincipalModal" id="cboResPrincipalModal" class="select-require" required>
                        <option value="">Seleccione</option>
                        @foreach (Usuario item in ViewBag.ListaUsuario)
                        {
                            <option value="@item.CodUsuario">@item.Nombres</option>
                        }
                    </select>
                </div>
            </div>

            <div class="col s12 m6 l4">
                <div class="input-field input-field-common col s12 disabled">
                    <label class="label active" for="cboResAlternoModal">Responsable Alterno</label>
                    <select name="cboResAlternoModal" id="cboResAlternoModal">
                        <option value="">Seleccione</option>
                        @foreach (Usuario item in ViewBag.ListaUsuario)
                        {
                            <option value="@item.CodUsuario">@item.Nombres</option>
                        }
                    </select>
                </div>
            </div>

            <div class="col s12 m6 l4">
                <div class="input-field input-field-common col s12 disabled">
                    <i class="material-icons icon-suffix">date_range</i>
                    <input name="dt-prox-vencimiento" id="dt-prox-vencimiento" type="text" class="datepicker" required>
                    <label for="dt-prox-vencimiento" class="label active">Próximo Vencimiento</label>
                </div>
            </div>
            
        </div>
        <div class="row">

            <div class="col s12 m6 l3">
                <div class="input-field input-field-common col s12">
                    <label class="label active" for="cboEstadoEnvioModal">Estado Envío *</label>
                    <select name="cboEstadoEnvioModal" id="cboEstadoEnvioModal" class="select-require" required>
                        <option value="1">Enviado</option>
                        <option value="0">No enviado</option>
                    </select>
                </div>
            </div>
            <div class="col s12 m6 l3">
                <div class="input-field input-field-common col s12">
                    <i class="material-icons icon-suffix">date_range</i>
                    <input name="dt-fecha-envio" id="dt-fecha-envio" type="text" class="datepicker" required>
                    <label for="dt-fecha-envio" class="label active">Fecha de Envío</label>
                </div>
            </div>

            <div class="col s12 m6 l6" id="divMotivoConsulta">
                <div class="input-field input-field-common col s12">
                    <label class="label active" for="motivos">Motivo Incumplimiento</label>
                    <textarea id="motivos" name="motivos" type="text" maxlength="500" class="materialize-textarea" disabled></textarea>
                </div>
            </div>

            <div class="col s12 m6 l6" id="divMotivoNuevo">
                <div class="input-field input-field-common col s12">
                    <label class="label active" for="cboMotivoModal">Motivo Incumplimiento</label>
                    <select name="cboMotivoModal" id="cboMotivoModal">

                        <option value="">Seleccione</option>
                        @foreach (Parametro item in ViewBag.ListaMotivo)
                        {

                            <option value="@item.CodigoElemento">@item.Descripcion</option>

                        }
                    </select>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col s12 m6 l8">
                <div class="input-field input-field-common col s12">
                    <label class="label active" for="comentarios">Comentarios</label>
                    <textarea id="comentarios" name="comentarios" type="text" maxlength="500" class="materialize-textarea"></textarea>
                </div>
            </div>

            <div class="col s12 m6 l4" id="divSustentoNuevo">
                <div class="file-field-content input-field input-field-common col s12">
                    <i class="material-icons icon-suffix">attach_file</i>
                    <label class="label active" for="sustentoEnvio">Sustento *</label>
                    @*<i class="material-icons file-field-icon on" id="btnLimpiarAdjunto">close</i>*@
                    <div class="file-field input-field">
                        <input type="file" id="sustentoEnvio" accept="application/pdf" name="sustentoEnvio" required>
                        <div class="file-path-wrapper">
                            <input class="file-path validate" type="text" id="sustentoEnvioAux" required>
                        </div>
                    </div>
                </div>
            </div> 
            <div class="col s12 m6 l4" id="divSustentoConsulta">
                <label class="label active">Sustento</label>
                <div>
                    <button class="btn waves-effect waves-light btn-war" @*onclick="location.href='/ExportarSustento?codigoSustento=22222'"*@ id="btnExportarSustento">
                        <i class="material-icons prefix" style="font-size:29px; padding: 0px 10px;">description</i>
                        <span style="font-size:15px;" id="nombreArchivo">Documento_proyecto.doc</span> <br />
                        <small style="color:#0288d1"></small>
                    </button>
                </div>
                
            </div>
        </div>
        <div class="row">
            <div class="col s12 m6 l8 offset-l2" id="divTextoDPlazo">
                <div class="input-field input-field-common col s12">
                    <p class="center-align" style="color:green">
                        <span class="texto-mensaje-plazo">¡Reporte enviado en el plazo correcto!</span>
                        <i class="material-icons small icon-demo green-text">mood</i>
                    </p>
                </div>
            </div>
            <div class="col s12 m6 l8 offset-l2" id="divTextoFPlazo">
                <div class="input-field input-field-common col s12">
                    <p class="center-align" style="color:red">
                        <span class="texto-mensaje-plazo">¡Reporte enviado fuera del plazo!</span>
                        <i class="material-icons small icon-demo red-text">mood_bad</i>
                    </p>
                </div>
            </div>
        </div>
    </div>

    <div class="modal-content content-input" id="divAcciones">
        <div class="row " style="margin-top:15px;">
            <div class="col s6 m2 l2 offset-m8 offset-l8">
                <button id="btnRegistrarEnvioModal" class="btn waves-effect waves-light btn-default btn-block">
                    <span>Registrar</span>
                    <i class="material-icons prefix">check</i>
                </button>
            </div>
            <div class="col s6 m2 l2">
                <button id="btnCancelarEnvioModal" class="btn waves-effect waves-light btn-warning modal-action modal-close btn-block">
                    <span>Cancelar</span>
                </button>
            </div>
        </div>
    </div>


</div>

}

Agrobanco.SCC/Agrobanco.SCC.Web/Views/Cumplimiento/_ListaCumplimiento.cshtml
@using PagedList;
@using PagedList.Mvc;
@using Agrobanco.SCC.Web.Models;
@model IPagedList<EnvioModel>

<div class="col s6 m3 l2">
    <a class="a-link" id="btnExcel" name="btnExcel" href="@(Url.Action("ExportarExcel"))?listaEntidad=@(ViewBag.hdListaEntidad)&listaFrecuencia=@(ViewBag.hdListaFrecuencia)&fecVencimientoDesde=@(ViewBag.fecVencimientoDesde)&fecVencimientoHasta=@(ViewBag.fecVencimientoHasta)">
        <i class="material-icons prefix">image_as_pdf</i>
        <span>Exportar EXCEL</span>
    </a>
</div>

<div class="col s6 m6 l12 right-align text-right">
    <ul class="pagination no-margin">

        @Html.PagedListPager(Model,
                                page => Url.Action("Buscar",
                                                    new { page = page, hdListaEntidad = ViewBag.hdListaEntidad, hdListaFrecuencia = ViewBag.hdListaFrecuencia, fecVencimientoDesde = ViewBag.fecVencimientoDesde, fecVencimientoHasta = ViewBag.fecVencimientoHasta }
                                        ),
                                PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "POST", UpdateTargetId = "cumplimiento-grid", LoadingElementId = "modal_loading_agro" }))
    </ul>
</div>

<div class="col s12 table-listas">
    <div class="table-common table-common-mediano">
        <div class="row row-title hide-on-small-only no-pad-bot">

            <div class="col s12 m2">Reporte</div>
            <div class="col s12 m2">Entidad</div>
            <div class="col s12 m2">Área Responsable</div>
            <div class="col s12 m1">Responsable Principal</div>
            <div class="col s12 m2">Frecuencia</div>
            <div class="col s12 m1">Vencimiento</div>
            <div class="col s12 m1">Envío</div>
            <div class="col s12 m1">Ver</div>
        </div>

        @foreach (var item in Model)
        {
        <div class="row">
            <div class="col s12 m2">
                <p>@Html.DisplayFor(modelItem => item.NombreReporte)</p>
            </div>
            <div class="col s12 m2">
                @Html.DisplayFor(modelItem => item.Entidad)
            </div>
            <div class="col s12 m2">
                @Html.DisplayFor(modelItem => item.AreaResponsable)
            </div>
            <div class="col s12 m1">
                @Html.DisplayFor(modelItem => item.ResponsablePrincipal)
            </div>
            <div class="col s12 m2">
                @Html.DisplayFor(modelItem => item.Frecuencia)
            </div>
            <div class="col s12 m1">
                @Html.DisplayFor(modelItem => item.FechaVencimiento)
            </div>
            <div class="col s12 m1">
                @Html.DisplayFor(modelItem => item.FechaEnvio)
            </div>
            <div class="col s12 m1">
                <i onclick="cumplimiento.Funciones.OpenEnvioModal(2,'@item.CodEnvio')" class="material-icons" style="cursor: pointer;" name="action">visibility</i>
            </div>
        </div>
        }
    </div>
</div>