Agrobanco.SCC/Agrobanco.SCC.Web/Controllers/SeguimientoController.cs
using Agrobanco.SCC.BLL;
using Agrobanco.SCC.DAL.Entidades;
using Agrobanco.SCC.Web.Models;
using ClosedXML.Excel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Agrobanco.SCC.Web.Controllers
{
    public class SeguimientoController : BaseController
    {
        // GET: Seguimiento
        public ActionResult Index()
        {
            CargarDatosIniciales();

            List<SeguimientoModel> seguimientoModel = new List<SeguimientoModel>();

            ViewBag.listaArea = "0";
            ViewBag.fecVencimientoDesde = null;
            ViewBag.fecVencimientoHasta = null;
            ViewBag.estadoCumplimiento = "4";

            seguimientoModel = ObtenerListaSeguimientoModel(null, null, null, "4");

            return View(seguimientoModel);
        }

        private void CargarDatosIniciales()
        {
            ParametriaBLL parametria = new ParametriaBLL();
            List<ElementoBasico> areasFiltro = new List<ElementoBasico>();
            var areas = parametria.ObtenerListaArea();
            var listaEstadoCumplimiento = new List<ElementoBasico>();
            listaEstadoCumplimiento.Add(new ElementoBasico { Codigo = "1", Descripcion = "Dentro del Plazo" });
            listaEstadoCumplimiento.Add(new ElementoBasico { Codigo = "2", Descripcion = "Fuera de Plazo" });
            listaEstadoCumplimiento.Add(new ElementoBasico { Codigo = "3", Descripcion = "No enviado" });
            listaEstadoCumplimiento.Add(new ElementoBasico { Codigo = "4", Descripcion = "No informado" });


            foreach (var item in areas)
            {
                ElementoBasico elemento = new ElementoBasico();
                elemento.Codigo = item.CodigoElemento.ToString();
                elemento.Descripcion = item.Descripcion;

                areasFiltro.Add(elemento);
            }

            ViewBag.ListaAreaResponsable = areasFiltro;
            ViewBag.ListaEstadoCumplimiento = listaEstadoCumplimiento;
        }

        [HttpPost]
        public ActionResult Buscar(string hdListaArea, string fecVencimientoDesde, string fecVencimientoHasta, string estadoCumplimiento)
        {
            List<SeguimientoModel> listaSeguimiento = new List<SeguimientoModel>();            

            ViewBag.listaArea = hdListaArea;
            ViewBag.fecVencimientoDesde = fecVencimientoDesde;
            ViewBag.fecVencimientoHasta = fecVencimientoHasta;
            ViewBag.estadoCumplimiento = estadoCumplimiento;
            try
            {
                listaSeguimiento = ObtenerListaSeguimientoModel(hdListaArea, fecVencimientoDesde, fecVencimientoHasta, estadoCumplimiento);

                return PartialView("_ListaSeguimiento", listaSeguimiento);
            }
            catch (Exception ex)
            {
                GenerarLog(ex.Message);
                throw new HttpException(500, ex.Message);
            }
            
        }

        private List<SeguimientoModel> ObtenerListaSeguimientoModel(string listaArea, string vencimientoDesde, string vencimientoHasta, string estadoCumplimiento)
        {
            List<SeguimientoModel> listaSeguimiento = new List<SeguimientoModel>();

            var reportes = ObtenerListaSeguimiento(listaArea, vencimientoDesde, vencimientoHasta, estadoCumplimiento);

            foreach (var item in reportes)
            {
                SeguimientoModel reporteModel = new SeguimientoModel();
                
                reporteModel.CodReporte = item.CodigoReporte;
                reporteModel.Nombre = item.NombreReporte;
                reporteModel.Descripcion = item.Descripcion;
                reporteModel.Entidad = item.Empresa;
                reporteModel.AreaResponsable = item.AreaResponsable;
                reporteModel.ResponsablePrincipal = item.ResponsablePrincipal;
                reporteModel.Frecuencia = item.Frecuencia;
                reporteModel.FechaVencimiento = string.Concat(item.ProximoVencimiento.Day.ToString().PadLeft(2, '0'), "/", item.ProximoVencimiento.Month.ToString().PadLeft(2, '0'), "/", item.ProximoVencimiento.Year.ToString());
                
                if (item.FechaVencimiento.HasValue)
                {
                    string dia = item.FechaVencimiento.Value.Day.ToString().PadLeft(2, '0');
                    string mes = item.FechaVencimiento.Value.Month.ToString().PadLeft(2, '0');
                    string anio = item.FechaVencimiento.Value.Year.ToString();

                    reporteModel.FechaVencimiento = string.Concat(dia, "/", mes, "/", anio);
                }

                reporteModel.FechaEnvio = string.Empty;

                if (item.FechaEnvio.HasValue)
                {
                    string dia = item.FechaEnvio.Value.Day.ToString().PadLeft(2, '0');
                    string mes = item.FechaEnvio.Value.Month.ToString().PadLeft(2, '0');
                    string anio = item.FechaEnvio.Value.Year.ToString();

                    reporteModel.FechaEnvio = string.Concat(dia, "/", mes, "/", anio);
                }

                reporteModel.FechaRegistro = string.Empty;

                if (item.FechaRegistro.HasValue)
                {
                    string dia = item.FechaRegistro.Value.Day.ToString().PadLeft(2, '0');
                    string mes = item.FechaRegistro.Value.Month.ToString().PadLeft(2, '0');
                    string anio = item.FechaRegistro.Value.Year.ToString();

                    reporteModel.FechaRegistro = string.Concat(dia, "/", mes, "/", anio);
                }

                reporteModel.EstadoCumplimiento = item.Cumplimiento.ToString();                

                listaSeguimiento.Add(reporteModel);
            }

            return listaSeguimiento;
        }

        private List<SeguimientoConsulta> ObtenerListaSeguimiento(string listaArea, string vencimientoDesde, string vencimientoHasta, string estadoCumplimiento)
        {
            SeguimientoBLL seguimientoBLL = new SeguimientoBLL();
            int? codEstadoCumplimiento = null;
            DateTime? dtVencimientoDesde = null;
            DateTime? dtVencimientoHasta = null;

            if (!string.IsNullOrEmpty(vencimientoDesde))
            {

                string[] arrFecha = vencimientoDesde.Split('/');
                string dia = arrFecha[0];
                string mes = arrFecha[1];
                string anio = arrFecha[2];

                dtVencimientoDesde = new DateTime(Convert.ToInt32(anio), Convert.ToInt32(mes), Convert.ToInt32(dia));
            }

            if (!string.IsNullOrEmpty(vencimientoHasta))
            {
                string[] arrFecha = vencimientoHasta.Split('/');
                string dia = arrFecha[0];
                string mes = arrFecha[1];
                string anio = arrFecha[2];

                dtVencimientoHasta = new DateTime(Convert.ToInt32(anio), Convert.ToInt32(mes), Convert.ToInt32(dia));
            }

            if (string.IsNullOrEmpty(listaArea))
            {
                listaArea = "0";
            }

            if (!string.IsNullOrEmpty(estadoCumplimiento))
            {
                codEstadoCumplimiento = Convert.ToInt32(estadoCumplimiento);
            }

            return seguimientoBLL.ObtenerListaSeguimiento(listaArea, dtVencimientoDesde, dtVencimientoHasta, codEstadoCumplimiento);
        }

        public void ExportarExcel(string listaArea, string fecVencimientoDesde, string fecVencimientoHasta, string estadoCumplimiento)
        {
            var reportes = ObtenerListaSeguimiento(listaArea, fecVencimientoDesde, fecVencimientoHasta, estadoCumplimiento);
            
            string fileNameReport = "ReporteSeguimiento_" + DateTime.Now.ToString("ddMMyyyy") + "_" + DateTime.Now.ToString("HHmmss");

            GenerarExcelResponse(fileNameReport, "Hoja1", reportes, (ws, data) => {

                int rowIndex = 1;
                int lastColumn = 25;
                ws.Range(rowIndex, 1, rowIndex, lastColumn).Style.Font.Bold = true;
                ws.Range(rowIndex, 1, rowIndex, lastColumn).Style.Border.SetOutsideBorder(XLBorderStyleValues.Thin);
                ws.Range(rowIndex, 1, rowIndex, lastColumn).Style.Border.SetInsideBorder(XLBorderStyleValues.Thin);

                ws.Cell(rowIndex, 1).Value = "Nombre Reporte";
                ws.Cell(rowIndex, 2).Value = "Descripción de Reporte";
                ws.Cell(rowIndex, 3).Value = "Medio de Envío";
                ws.Cell(rowIndex, 4).Value = "Entidad";
                ws.Cell(rowIndex, 5).Value = "Área Responsable de Generación";
                ws.Cell(rowIndex, 6).Value = "Gerente Responsable de Generación";
                ws.Cell(rowIndex, 7).Value = "Responsable de Generación 1";
                ws.Cell(rowIndex, 8).Value = "Responsable de Generación 2";
                ws.Cell(rowIndex, 9).Value = "Área Responsable";
                ws.Cell(rowIndex, 10).Value = "Coordinador Responsable";
                ws.Cell(rowIndex, 11).Value = "Responsable Principal";
                ws.Cell(rowIndex, 12).Value = "Responsable Alterno";
                ws.Cell(rowIndex, 13).Value = "Gerente Responsable";
                ws.Cell(rowIndex, 14).Value = "Frecuencia del Reporte";
                ws.Cell(rowIndex, 15).Value = "Plazo (días)";
                ws.Cell(rowIndex, 16).Value = "Tipo días de plazo";
                ws.Cell(rowIndex, 17).Value = "Vencimiento";
                ws.Cell(rowIndex, 18).Value = "MES";
                ws.Cell(rowIndex, 19).Value = "AÑO";
                ws.Cell(rowIndex, 20).Value = "Fecha Envío";
                ws.Cell(rowIndex, 21).Value = "Fecha Registro";
                ws.Cell(rowIndex, 22).Value = "Motivo Incumplimiento";
                ws.Cell(rowIndex, 23).Value = "Comentarios";
                ws.Cell(rowIndex, 24).Value = "Cumplimiento";

                ws.Columns().AdjustToContents();

Agrobanco.SCC/Agrobanco.SCC.Web/Views/Seguimiento/Index.cshtml
@using Agrobanco.SCC.Web.Models;
@model IEnumerable<SeguimientoModel>
@{
    ViewBag.Title = "Index";
    List<ElementoBasico> areasResponsables = ViewBag.ListaAreaResponsable;
    List<ElementoBasico> listaEstadoCumplimiento = ViewBag.ListaEstadoCumplimiento;

}

<div class="section no-padding">
    <div class="row col s12 no-mar-bot">
        <div class="section no-mar-bot">
            <div class="col s12 m12 l12">
                <h1 class="title">Seguimiento</h1>
            </div>
        </div>
    </div>
</div>

<div class="card-panel row layout-card-gray-2">
    <div class="row">
        <div class="col s12 m12 l12">
            <span class="card-panel-title">Buscar por:</span>
        </div>
    </div>

    <div class="row no-mar-bot">
        @using (Ajax.BeginForm("Buscar", "Seguimiento",
               new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "seguimiento-grid", LoadingElementId = "modal_loading_agro",
                   OnFailure = "app.Funciones.msgError('Ha ocurrido un error en la aplicación')" }))
        {
            <input type="hidden" id="hdListaArea" name="hdListaArea" value="0" />

            <div class="col s12 m6 l4">
                <div class="input-field input-field-common col s12">
                    <label class="label active" for="cbo-area-responsable">Área Responsable</label>
                    <select name="cbo-area-responsable" id="cbo-area-responsable" multiple>
                        <option value="" disabled selected>Seleccione</option>
                        @foreach (var item in areasResponsables)
                        {

                            <option value="@item.Codigo">@item.Descripcion</option>
                        }
                    </select>
                </div>
            </div>
            <div class="col s12 m6 l2">
                <div class="input-field input-field-common col s12">
                    <i class="material-icons icon-suffix">date_range</i>
                    <input name="fecVencimientoDesde" id="fecVencimientoDesde" type="text" class="datepicker">
                    <label for="fecVencimientoDesde" class="label active">Vencimiento (Desde)</label>
                </div>
            </div>
            <div class="col s12 m6 l2">
                <div class="input-field input-field-common col s12">
                    <i class="material-icons icon-suffix">date_range</i>
                    <input name="fecVencimientoHasta" id="fecVencimientoHasta" type="text" class="datepicker">
                    <label for="fecVencimientoHasta" class="label active">Vencimiento (Hasta)</label>
                </div>
            </div>
            <div class="col s12 m6 l2">
                <div class="input-field input-field-common col s12">
                    <label class="label active" for="estadoCumplimiento">Cumplimiento</label>
                    <select name="estadoCumplimiento" id="estadoCumplimiento">
                        <option value="" selected>Seleccione</option>
                        @foreach (var item in listaEstadoCumplimiento)
                        {
                            <option value="@item.Codigo">@item.Descripcion</option>
                        }
                    </select>
                </div>
            </div>

            <div class="col s2 m6 l2 offset-s7">
                <button id="btnBuscar" class="btn waves-effect waves-light btn-default-resize " style="margin-top:23px;">
                    <span>Buscar</span>
                    <i class="material-icons">search</i>
                </button>
            </div>
        }

    </div>
</div>

<div class="row" id="seguimiento-grid">
    @{
        Html.RenderPartial("_ListaSeguimiento", Model);
    }
</div>

@section scripts{
    @Scripts.Render("~/Scripts/app/Seguimiento.js")
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
}

Agrobanco.SCC/Agrobanco.SCC.Web/Views/Seguimiento/_ListaSeguimiento.cshtml
@using PagedList;
@using PagedList.Mvc;
@using Agrobanco.SCC.Web.Models;
@model IEnumerable<SeguimientoModel>

<div class="col s6 m3 l2">
    <a class="a-link" id="btnPdf" name="btnPdf" href="@(Url.Action("ExportarExcel"))?listaArea=@(ViewBag.listaArea)&fecVencimientoDesde=@(ViewBag.fecVencimientoDesde)&fecVencimientoHasta=@(ViewBag.fecVencimientoHasta)&estadoCumplimiento=@(ViewBag.estadoCumplimiento)">
        <i class="material-icons prefix">image_as_pdf</i>
        <span>Exportar EXCEL</span>
    </a>
</div>

<div class="col s12 table-listas">
    <div class="table-common table-common-mediano">
        <div class="row row-title hide-on-small-only no-pad-bot">

            <div class="col s12 m2">Reporte</div>
            <div class="col s12 m2">Entidad</div>
            <div class="col s12 m2">Área Responsable</div>
            <div class="col s12 m1">Responsable Principal</div>
            <div class="col s12 m1">Frecuencia</div>
            <div class="col s12 m1">Vencimiento</div>
            <div class="col s12 m1">Envío</div>
            <div class="col s12 m1">Registro</div>
            <div class="col s12 m1">Cumplimiento</div>
        </div>

        @foreach (var item in Model)
        {
        <div class="row">
            <div class="col s12 m2">
                <p>@Html.DisplayFor(modelItem => item.Nombre)</p>
                <p>@Html.DisplayFor(modelItem => item.Descripcion)</p>
            </div>
            <div class="col s12 m2">
                @Html.DisplayFor(modelItem => item.Entidad)
            </div>
            <div class="col s12 m2">
                @Html.DisplayFor(modelItem => item.AreaResponsable)
            </div>
            <div class="col s12 m1">
                @Html.DisplayFor(modelItem => item.ResponsablePrincipal)
            </div>
            <div class="col s12 m1">
                @Html.DisplayFor(modelItem => item.Frecuencia)
            </div>
            <div class="col s12 m1">
                @Html.DisplayFor(modelItem => item.FechaVencimiento)
            </div>
            <div class="col s12 m1">
                @Html.DisplayFor(modelItem => item.FechaEnvio)
            </div>
            <div class="col s12 m1">
                @Html.DisplayFor(modelItem => item.FechaRegistro)
            </div>
            <div class="col s12 m1">
                <div class="col s6 offset-s2">

                    @if (item.EstadoCumplimiento == "1")
                    {
                        <i class="material-icons" title="Dentro del plazo" style="cursor:pointer; color:green">check_circle</i>
                    }

                    @if (item.EstadoCumplimiento == "2")
                    {
                        <i class="material-icons" title="Fuera del plazo" style="cursor:pointer; color:red">highlight_off</i>
                    }

                    @if (item.EstadoCumplimiento == "3")
                    {
                        <i class="material-icons" title="No enviado" style="cursor:pointer; color:blue">do_not_disturb_on</i>
                    }

                    @if (item.EstadoCumplimiento == "4")
                    {
                        <i class="material-icons" title="No informado" style="cursor:pointer; color:black">radio_button_unchecked</i>
                    }

                </div>
            </div>
        </div>
        }
    </div>
</div>